
import Algoritmos.Disco;
import Algoritmos.DiscoView;
import Algoritmos.FifoView;
import Algoritmos.LamportView;
import Algoritmos.SwappingView;
import Procesos.Proceso;
import Procesos.ProcesoTableModel;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Augusto
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ArrayList<Proceso> listProcess;
    private ProcesoTableModel ptm;
    private String algoritmoSeleccionado = "";
    private ArrayList<Integer> listadoPeticiones;
    public Principal() {
        initComponents();
        jPanelDisco.setVisible(false);
        jPanelAlgoritmoPlanificacion.setVisible(false);
        mensajeError.setVisible(false);
        groupButton();
        ArrayList<Proceso> listado = new ArrayList();
       int orden = 10;
        for (int i = 0; i < 10; i++) {
            Proceso p = new Proceso();
            p.setTiempoLlegada(orden);
            p.setNombre("p"+i);
            p.setRafagaCpu(2);
            orden -= 1;
            listado.add(p);
        }
        ptm = new ProcesoTableModel(listado);
        jTAListDisc.setText("");
        jTableProcesos.setModel(ptm);
        listadoPeticiones = new ArrayList<Integer>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAbout = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jDocumentation = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPopUpMenuTable = new javax.swing.JPopupMenu();
        jItemAgregarFila = new javax.swing.JMenuItem();
        jItemEliminarFila = new javax.swing.JMenuItem();
        jDetalleAlgoritmoFifo = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jDetalleAlgoritmoSwapping = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jDetalleAlgoritmoSSTF = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jDetalleAlgoritmoDekker = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jDetalleAlgoritmoPeterson = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jDetalleAlgoritmoLamport = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jDetalleAlgoritmoLRU = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jDetalleAlgoritmoLook = new javax.swing.JDialog();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jDetalleAlgoritmoScan = new javax.swing.JDialog();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jDetalleAlgoritmocScan = new javax.swing.JDialog();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanelAlgoritmoPlanificacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAlgoritmoSeleccionado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSimular = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRBFifo = new javax.swing.JRadioButton();
        jRBSSFT = new javax.swing.JRadioButton();
        jRBLook = new javax.swing.JRadioButton();
        jButtonDetalleFIFO = new javax.swing.JButton();
        jButtonDetalleScan = new javax.swing.JButton();
        jButtonDetalleLook = new javax.swing.JButton();
        jRBLRU = new javax.swing.JRadioButton();
        jRBLamport = new javax.swing.JRadioButton();
        jButtonDetalleSwapping = new javax.swing.JButton();
        jButtonDetalleLRU = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jRBSwapping = new javax.swing.JRadioButton();
        jButtonDetalleSwapping1 = new javax.swing.JButton();
        jRBSwapping1 = new javax.swing.JRadioButton();
        jRBDekker = new javax.swing.JRadioButton();
        jButtonDetalleSwapping2 = new javax.swing.JButton();
        cScan = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        SCAN = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanelDisco = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAListDisc = new javax.swing.JTextArea();
        jTextFieldPosicionDisco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPeticionPos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jAbout.setTitle("Acerca de ");
        jAbout.setMinimumSize(new java.awt.Dimension(618, 400));
        jAbout.setModal(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Colaboradores del Proyecto:\n*\n*\n*\n*");
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel5.setText("Simulator");

        jLabel7.setText("Version 1.0");

        jLabel6.setText("Este programa fue creado con fines ...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jButton13.setLabel("CERRAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAboutLayout = new javax.swing.GroupLayout(jAbout.getContentPane());
        jAbout.getContentPane().setLayout(jAboutLayout);
        jAboutLayout.setHorizontalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAboutLayout.createSequentialGroup()
                .addGroup(jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jAboutLayout.createSequentialGroup()
                        .addGroup(jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAboutLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)))
                            .addGroup(jAboutLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jAboutLayout.setVerticalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jDocumentation.setMinimumSize(new java.awt.Dimension(576, 323));
        jDocumentation.setModal(true);

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel8.setText("Documentacion");

        jLabel9.setText("aca debe cargar un pdf visible con la documentacion");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(116, 116, 116))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel9)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jButton14.setText("CERRAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDocumentationLayout = new javax.swing.GroupLayout(jDocumentation.getContentPane());
        jDocumentation.getContentPane().setLayout(jDocumentationLayout);
        jDocumentationLayout.setHorizontalGroup(
            jDocumentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDocumentationLayout.createSequentialGroup()
                .addGroup(jDocumentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDocumentationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDocumentationLayout.createSequentialGroup()
                        .addGroup(jDocumentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDocumentationLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel8))
                            .addGroup(jDocumentationLayout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jButton14)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDocumentationLayout.setVerticalGroup(
            jDocumentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDocumentationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jItemAgregarFila.setText("Agregar Fila");
        jItemAgregarFila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jItemAgregarFilaMouseClicked(evt);
            }
        });
        jItemAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemAgregarFilaActionPerformed(evt);
            }
        });
        jPopUpMenuTable.add(jItemAgregarFila);

        jItemEliminarFila.setText("Eliminar Fila");
        jItemEliminarFila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jItemEliminarFilaMouseClicked(evt);
            }
        });
        jItemEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEliminarFilaActionPerformed(evt);
            }
        });
        jPopUpMenuTable.add(jItemEliminarFila);

        jDetalleAlgoritmoFifo.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoFifo.setSize(new java.awt.Dimension(550, 450));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("En este método el sistema operativo sólo tiene que guardar en qué \norden las páginas fueron cargadas, de modo que al necesitar hacer\nespacio pueda fácilmente elegir la primera página cargada. Se usa \nuna cola, al cargar una página nueva se ingresa en el último lugar. \nAunquelas colas FIFO son simples e intuitivas, no se comportan de \nmanera aceptable en la aplicación práctica, por lo que es raro su uso\nen su forma simple. Uno de los problemas que presentan \nes la llamada Anomalía FIFO oAnomalía de Belady. Belady encontró\nejemplos en los que un sistema con un número de marcos de páginas\nigual a tres tenía menos fallosde páginas que un sistema con cuatro \nmarcos de páginas. El problema consiste en que podemos quitar de \nmemoria una página de memoria muy usada, sólo porque es la más\nantigua");
        jTextArea2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea2.setPreferredSize(new java.awt.Dimension(350, 250));
        jScrollPane4.setViewportView(jTextArea2);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("              Primero en Entrar Pimero En Salir (FIFO)");

        javax.swing.GroupLayout jDetalleAlgoritmoFifoLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoFifo.getContentPane());
        jDetalleAlgoritmoFifo.getContentPane().setLayout(jDetalleAlgoritmoFifoLayout);
        jDetalleAlgoritmoFifoLayout.setHorizontalGroup(
            jDetalleAlgoritmoFifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoFifoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jDetalleAlgoritmoFifoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jDetalleAlgoritmoFifoLayout.setVerticalGroup(
            jDetalleAlgoritmoFifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoFifoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoSwapping.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoSwapping.setSize(new java.awt.Dimension(570, 490));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("La mayoría de los sistemas operativos modernos poseen un mecanismo\nllamado memoria virtual, que permite hacer creer a los programas que \ntienen más memoria que la disponible realmente. Como en realidad no \nse tiene físicamente toda esa memoria, algunos procesos no podrán ser\nubicados en la memoria RAM.\nEn este caso es cuando es útil el espacio de intercambio: el sistema \noperativo puede buscar un proceso poco activo, y moverlo al área de \nintercambio (el disco duro) y de esa forma liberar la memoria principal\npara cargar otros procesos. Mientras no haga falta, el proceso extraído\nde memoria puede quedarse en el disco, ya que ahí no utiliza memoria\nfísica. Cuando sea necesario, el sistema vuelve a hacer un intercambio,\npasándolo del disco a memoria RAM. Es un proceso lento (comparado \ncon usar sólo la memoria RAM), pero permite dar la impresión de que \nhay más memoria disponible.");
        jTextArea3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea3.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane5.setViewportView(jTextArea3);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("           Swapping");

        javax.swing.GroupLayout jDetalleAlgoritmoSwappingLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoSwapping.getContentPane());
        jDetalleAlgoritmoSwapping.getContentPane().setLayout(jDetalleAlgoritmoSwappingLayout);
        jDetalleAlgoritmoSwappingLayout.setHorizontalGroup(
            jDetalleAlgoritmoSwappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoSwappingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoSwappingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jDetalleAlgoritmoSwappingLayout.setVerticalGroup(
            jDetalleAlgoritmoSwappingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoSwappingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoSSTF.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoSSTF.setSize(new java.awt.Dimension(590, 450));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Es un algoritmo de planificación de E/S para dispositivos de bloques (dis-\ncos duros).\nEs una mejora directa del algoritmo FIFO para planificación de E/S. \nLa unidad mantiene un buffer de peticiones entrantes, y junto a éstas se\nañade un número que indica el cilindro al que tienen que acceder. Cuan-\nto más pequeño es el número significa que el cilindro está más cerca del\neje.\nTiene la ventaja de ser un algoritmo muy simple y que mejora claramen-\nte el método FIFO, en el sentido de que reduce drásticamente el núme-\nro de saltos que tiene que realizar el cabezal haciendo que el tiempo me-\ndio de respuesta se reduzca.\nEs la planificación que ocupa un menor número de movimientos del cabe-\nzal en la mayoría de los casos a resolver.\n\n");
        jTextArea4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea4.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane6.setViewportView(jTextArea4);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText(" La Busqueda Mas Corta Primero (SSTF)");

        javax.swing.GroupLayout jDetalleAlgoritmoSSTFLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoSSTF.getContentPane());
        jDetalleAlgoritmoSSTF.getContentPane().setLayout(jDetalleAlgoritmoSSTFLayout);
        jDetalleAlgoritmoSSTFLayout.setHorizontalGroup(
            jDetalleAlgoritmoSSTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoSSTFLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(jDetalleAlgoritmoSSTFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6))
        );
        jDetalleAlgoritmoSSTFLayout.setVerticalGroup(
            jDetalleAlgoritmoSSTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoSSTFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoDekker.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoDekker.setSize(new java.awt.Dimension(590, 450));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("Es un algoritmo de programación concurrente para exclusión mutua, que\npermite a dos procesos o hilos de ejecución compartir un recurso sin con-\nflictos. Fue uno de los primeros algoritmos de exclusión mutua inventados\n, implementado por Edsger Dijkstra.\nSi ambos procesos intentan acceder a la sección crítica simultáneamente,\nel algoritmo elige un proceso según una variable turno. Si el otro proceso\nestá ejecutando en su sección crítica, deberá esperar su finalización.\n \nExisten cinco versiones del algoritmo Dekker, teniendo ciertos fallos los \nprimeros cuatro. La versión 5 es la que trabaja más eficientemente, siendo\nuna combinación de la 1 y la 4.\n\n");
        jTextArea5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea5.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane7.setViewportView(jTextArea5);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Dekker");

        javax.swing.GroupLayout jDetalleAlgoritmoDekkerLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoDekker.getContentPane());
        jDetalleAlgoritmoDekker.getContentPane().setLayout(jDetalleAlgoritmoDekkerLayout);
        jDetalleAlgoritmoDekkerLayout.setHorizontalGroup(
            jDetalleAlgoritmoDekkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoDekkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(jDetalleAlgoritmoDekkerLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDetalleAlgoritmoDekkerLayout.setVerticalGroup(
            jDetalleAlgoritmoDekkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoDekkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoPeterson.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoPeterson.setSize(new java.awt.Dimension(590, 300));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Es un algoritmo de programación concurrente para exclusión mutua.\nPermite a dos o más procesos o hilos de ejecución compartir un recurso \nsin conflictos, utilizando sólo memoria compartida para la comunicación.\nEs aplicable a cualquier número de procesos con memoria compartida \ntanto del monoprocesador como de multiprocesador.\nEs simple y fácil de verificar.\nPuede usarse para varias secciones críticos.\n\n");
        jTextArea6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea6.setPreferredSize(new java.awt.Dimension(350, 180));
        jScrollPane8.setViewportView(jTextArea6);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText(" Peterson ");

        javax.swing.GroupLayout jDetalleAlgoritmoPetersonLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoPeterson.getContentPane());
        jDetalleAlgoritmoPeterson.getContentPane().setLayout(jDetalleAlgoritmoPetersonLayout);
        jDetalleAlgoritmoPetersonLayout.setHorizontalGroup(
            jDetalleAlgoritmoPetersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoPetersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(jDetalleAlgoritmoPetersonLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDetalleAlgoritmoPetersonLayout.setVerticalGroup(
            jDetalleAlgoritmoPetersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoPetersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDetalleAlgoritmoLamport.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoLamport.setSize(new java.awt.Dimension(590, 450));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Este algoritmo recibe el nombre de algoritmo del ascensor porque se com\nporta como tal: va atendiendo las solicitudes que va encontrando en el se\nntido en el que se van desplazando las cabezas de lectura/escritura por el\ndisco. Cuando no hay más solicitudes en ese sentido, o se llega al extremo\n, se invierte el sentido para hacer lo mismo otra vez, pero yendo hacia el \notro lado. Por tanto, en este algoritmo es necesario tener un bit que indi-\nque\nel sentido del movimiento.\nLas cabezas se mueven de un extremo a otro del disco, atendiendo las so\nlicitudes que se van encontrando.\nSu ventaja es que tiene tiempos de servicio acotados, y más variables en \nlos extremos que en el centro.\n");
        jTextArea7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea7.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane9.setViewportView(jTextArea7);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Scan");

        javax.swing.GroupLayout jDetalleAlgoritmoLamportLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoLamport.getContentPane());
        jDetalleAlgoritmoLamport.getContentPane().setLayout(jDetalleAlgoritmoLamportLayout);
        jDetalleAlgoritmoLamportLayout.setHorizontalGroup(
            jDetalleAlgoritmoLamportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoLamportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(jDetalleAlgoritmoLamportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDetalleAlgoritmoLamportLayout.setVerticalGroup(
            jDetalleAlgoritmoLamportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoLamportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoLRU.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoLRU.setSize(new java.awt.Dimension(590, 450));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Es un algoritmo de reemplazo de página.\nAsume que las páginas recientemente usadas serán usadas de nuevo, \nelimina las páginas que no han sido usadas por mucho tiempo.\nReemplaza la página que no se haya referenciado desde hace más tiempo.\nLRU seleccionará como candidata la página de memoria que no se haya \nreferenciado desde hace más tiempo. Debido al principio de proximidad \nreferenciada, esta página sería la que tiene menos probabilidad de volver \na tener referencias en un futuro próximo.\nEs uno de los mejores y, al contrario que FIFO, no tiene la Anomalía de \nBelady (más fallos de página al aumentar el número de marcos en la me-\nmoria física).\n\n\n");
        jTextArea8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea8.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane10.setViewportView(jTextArea8);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Menos Usada Recientemente (LRU)");

        javax.swing.GroupLayout jDetalleAlgoritmoLRULayout = new javax.swing.GroupLayout(jDetalleAlgoritmoLRU.getContentPane());
        jDetalleAlgoritmoLRU.getContentPane().setLayout(jDetalleAlgoritmoLRULayout);
        jDetalleAlgoritmoLRULayout.setHorizontalGroup(
            jDetalleAlgoritmoLRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoLRULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(jDetalleAlgoritmoLRULayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDetalleAlgoritmoLRULayout.setVerticalGroup(
            jDetalleAlgoritmoLRULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoLRULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDetalleAlgoritmoLook.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoLook.setSize(new java.awt.Dimension(590, 300));

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("Las cabezas no se mueven hasta el extremo, sino hasta la última solicitud\npendiente en el sentido del movimiento.\nEl algoritmo LOOK es el mismo que el algoritmo SCAN en el sentido de \nque también respeta las solicitudes en ambas direcciones de barrido de la\ncabeza del disco, sin embargo, este algoritmo \"mira\" hacia adelante para\nver si hay solicitudes pendientes en la dirección del movimiento de la \ncabeza.\n");
        jTextArea10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea10.setPreferredSize(new java.awt.Dimension(350, 180));
        jScrollPane12.setViewportView(jTextArea10);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Look");

        javax.swing.GroupLayout jDetalleAlgoritmoLookLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoLook.getContentPane());
        jDetalleAlgoritmoLook.getContentPane().setLayout(jDetalleAlgoritmoLookLayout);
        jDetalleAlgoritmoLookLayout.setHorizontalGroup(
            jDetalleAlgoritmoLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoLookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoLookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(250, 250, 250))
        );
        jDetalleAlgoritmoLookLayout.setVerticalGroup(
            jDetalleAlgoritmoLookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoLookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDetalleAlgoritmoScan.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmoScan.setSize(new java.awt.Dimension(590, 450));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("La panadería de Lamport es un algoritmo basado en el sistema de turno \nexistente en las panaderías y otros negocios.\nConsiste en darle a cada cliente un número, el cual determina el orden de\natención del vendedor y permitirles realizar su pedido, después de lo cual\nse le libera, pudiendo este comprar nuevamente sólo si obtiene un núme-\nro nuevo.\nLlevado a programación, el Servidor entrega un número a cada hilo que \ndesea acceder a este y les atiende de uno en uno por orden de llegada. \nUna vez que toca le toca su turno, el proceso ingresa a su etapa crítica y \ndespués de realizada esta, el servidor le libera y atiende al siguiente proce-\nso.\nEn el modelo algorítmico que se propone, cada cliente es un hilo, identifi-\ncado con un número único i. Los hilos se deben coordinar para decidir en\ncada momento qué hilo tiene derecho a ejecutar su código de sección \ncrítica.");
        jTextArea9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea9.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane11.setViewportView(jTextArea9);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText(" Lamport (Bakery)");

        javax.swing.GroupLayout jDetalleAlgoritmoScanLayout = new javax.swing.GroupLayout(jDetalleAlgoritmoScan.getContentPane());
        jDetalleAlgoritmoScan.getContentPane().setLayout(jDetalleAlgoritmoScanLayout);
        jDetalleAlgoritmoScanLayout.setHorizontalGroup(
            jDetalleAlgoritmoScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmoScanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoScanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        jDetalleAlgoritmoScanLayout.setVerticalGroup(
            jDetalleAlgoritmoScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmoScanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDetalleAlgoritmocScan.setLocation(new java.awt.Point(650, 300));
        jDetalleAlgoritmocScan.setSize(new java.awt.Dimension(590, 450));

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("La planificación SCAN circular (C-SCAN) es una variante de SCAN diseñada\npara dar un tiempo de espera más uniforme. Al igual que SCAN, C-SCAN \nmueve la cabeza de un extremo del disco al otro, atendiendo las solicitu\ndes en el camino, sólo que ahora, cuando la cabeza llega al otro extremo,\nregresa de inmediato al principio del disco sin atender solicitudes.\nEl algoritmo de planificación C-SCAN básicamente trata los cilindros como\nuna lista circular que continúa del último cilindro al primero.\nEn la estrategia C-SCAN, el brazo se mueve del cilindro exterior al interior,\n sirviendo a las peticiones con menor tiempo de búsqueda. Cuando el \nbrazo ha completado su recorrido hacia adentro, salta a la petición más \ncercana al cilindro exterior y a continuación reanuda su recorrido hacia \nadentro procesando peticiones.\n");
        jTextArea11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea11.setPreferredSize(new java.awt.Dimension(350, 300));
        jScrollPane13.setViewportView(jTextArea11);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("C-Scan");

        javax.swing.GroupLayout jDetalleAlgoritmocScanLayout = new javax.swing.GroupLayout(jDetalleAlgoritmocScan.getContentPane());
        jDetalleAlgoritmocScan.getContentPane().setLayout(jDetalleAlgoritmocScanLayout);
        jDetalleAlgoritmocScanLayout.setHorizontalGroup(
            jDetalleAlgoritmocScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalleAlgoritmocScanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmocScanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jDetalleAlgoritmocScanLayout.setVerticalGroup(
            jDetalleAlgoritmocScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalleAlgoritmocScanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulator");

        jLabel1.setText("2) Procesos:");

        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                " ", "Proceso", "Tiempo de Llegada", "Rafaga", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProcesosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProcesos);

        jButton1.setText("EXPORTAR");

        jButton2.setText("IMPORTAR");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Notas"));

        jLabel2.setText("Aqui podrá elegir los procesos que se ejecutarán con el algoritmo posteriormente seleccionado.");

        jLabel3.setText("Campos necesarios para el algoritmo:");

        jLabelAlgoritmoSeleccionado.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAlgoritmoSeleccionado.setText("jLabel10");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAlgoritmoSeleccionado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelAlgoritmoSeleccionado))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAlgoritmoPlanificacionLayout = new javax.swing.GroupLayout(jPanelAlgoritmoPlanificacion);
        jPanelAlgoritmoPlanificacion.setLayout(jPanelAlgoritmoPlanificacionLayout);
        jPanelAlgoritmoPlanificacionLayout.setHorizontalGroup(
            jPanelAlgoritmoPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgoritmoPlanificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgoritmoPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlgoritmoPlanificacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanelAlgoritmoPlanificacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAlgoritmoPlanificacionLayout.setVerticalGroup(
            jPanelAlgoritmoPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgoritmoPlanificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAlgoritmoPlanificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSimular.setText("SIMULAR");
        jButtonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimularActionPerformed(evt);
            }
        });

        mensajeError.setForeground(new java.awt.Color(255, 51, 51));
        mensajeError.setText("Mensaje de Error");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jButtonSimular))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(mensajeError)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeError)
                .addGap(9, 9, 9)
                .addComponent(jButtonSimular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("1) Algoritmos:");

        jRBFifo.setText("FIFO");
        jRBFifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFifoActionPerformed(evt);
            }
        });

        jRBSSFT.setText("SSTF");
        jRBSSFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSSFTActionPerformed(evt);
            }
        });

        jRBLook.setText("LOOK");
        jRBLook.setEnabled(false);
        jRBLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLookActionPerformed(evt);
            }
        });

        jButtonDetalleFIFO.setText("Detalles");
        jButtonDetalleFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleFIFOActionPerformed(evt);
            }
        });

        jButtonDetalleScan.setText("Detalles");
        jButtonDetalleScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleScanActionPerformed(evt);
            }
        });

        jButtonDetalleLook.setText("Detalles");
        jButtonDetalleLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleLookActionPerformed(evt);
            }
        });

        jRBLRU.setText("LRU");
        jRBLRU.setEnabled(false);
        jRBLRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLRUActionPerformed(evt);
            }
        });

        jRBLamport.setText("LAMPORT");
        jRBLamport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLamportActionPerformed(evt);
            }
        });

        jButtonDetalleSwapping.setText("Detalles");
        jButtonDetalleSwapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleSwappingActionPerformed(evt);
            }
        });

        jButtonDetalleLRU.setText("Detalles");
        jButtonDetalleLRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleLRUActionPerformed(evt);
            }
        });

        jButton8.setText("Detalles");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jRBSwapping.setText("SWAPPING");
        jRBSwapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSwappingActionPerformed(evt);
            }
        });

        jButtonDetalleSwapping1.setText("Detalles");
        jButtonDetalleSwapping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleSwapping1ActionPerformed(evt);
            }
        });

        jRBSwapping1.setText("PETERSON");
        jRBSwapping1.setEnabled(false);
        jRBSwapping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSwapping1ActionPerformed(evt);
            }
        });

        jRBDekker.setText("DEKKER");
        jRBDekker.setEnabled(false);
        jRBDekker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDekkerActionPerformed(evt);
            }
        });

        jButtonDetalleSwapping2.setText("Detalles");
        jButtonDetalleSwapping2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleSwapping2ActionPerformed(evt);
            }
        });

        cScan.setText("C-SCAN");
        cScan.setEnabled(false);
        cScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cScanActionPerformed(evt);
            }
        });

        jButton9.setText("Detalles");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        SCAN.setText("SCAN");
        SCAN.setEnabled(false);
        SCAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCANActionPerformed(evt);
            }
        });

        jButton10.setText("Detalles");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRBFifo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBSSFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBSwapping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDetalleFIFO)
                            .addComponent(jButtonDetalleScan)
                            .addComponent(jButtonDetalleSwapping)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBLRU, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBLamport, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBLook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jRBSwapping1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDetalleLRU)
                        .addGap(18, 18, 18)
                        .addComponent(jRBDekker, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDetalleLook)
                        .addGap(18, 18, 18)
                        .addComponent(cScan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDetalleSwapping1)
                                .addGap(26, 26, 26)
                                .addComponent(SCAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetalleSwapping2)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBFifo)
                            .addComponent(jButtonDetalleFIFO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBSSFT)
                            .addComponent(jButtonDetalleScan)
                            .addComponent(jRBLRU)
                            .addComponent(jButtonDetalleLRU)
                            .addComponent(jRBDekker)
                            .addComponent(jButton8)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBSwapping1)
                                .addComponent(jButtonDetalleSwapping1)
                                .addComponent(SCAN)
                                .addComponent(jButtonDetalleSwapping2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBLamport)
                                .addComponent(jButton10)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBSwapping)
                            .addComponent(jButtonDetalleSwapping)
                            .addComponent(jRBLook)
                            .addComponent(jButtonDetalleLook)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cScan)
                            .addComponent(jButton9))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel11.setText("2) Posicion Inicial del cabezal del Disco:");

        jTAListDisc.setColumns(20);
        jTAListDisc.setRows(5);
        jScrollPane3.setViewportView(jTAListDisc);

        jLabel12.setText("3) Peticiones:");

        jLabel13.setText("Posicion:");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPeticionPos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPeticionPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDiscoLayout = new javax.swing.GroupLayout(jPanelDisco);
        jPanelDisco.setLayout(jPanelDiscoLayout);
        jPanelDiscoLayout.setHorizontalGroup(
            jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiscoLayout.createSequentialGroup()
                .addGroup(jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDiscoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDiscoLayout.createSequentialGroup()
                                .addGroup(jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDiscoLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldPosicionDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))
                                .addGap(20, 20, 20))
                            .addComponent(jScrollPane3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDiscoLayout.setVerticalGroup(
            jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPosicionDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Documentación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Acerca de");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 196, Short.MAX_VALUE))
                    .addComponent(jPanelDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAlgoritmoPlanificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAlgoritmoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jAbout.setAlwaysOnTop(true);
        jAbout.setLocationRelativeTo(null);
        jAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jRBSSFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSSFTActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "SSTF";
        jPanelDisco.setVisible(true);
        jPanelAlgoritmoPlanificacion.setVisible(false);
    }//GEN-LAST:event_jRBSSFTActionPerformed

    private void jRBLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLookActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "LOOK";
    }//GEN-LAST:event_jRBLookActionPerformed

    private void jRBLRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLRUActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "LRU";
    }//GEN-LAST:event_jRBLRUActionPerformed

    private void jRBLamportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLamportActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "LAMPORT";
    }//GEN-LAST:event_jRBLamportActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jAbout.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jDocumentation.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jDocumentation.setAlwaysOnTop(true);
        jDocumentation.setLocationRelativeTo(null);
        jDocumentation.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTableProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProcesosMouseClicked
        if(evt.getButton() == 3){
            jPopUpMenuTable.setLocation(evt.getLocationOnScreen());
            jPopUpMenuTable.show(evt.getComponent(), evt.getX(), evt.getY());
            jPopUpMenuTable.setVisible(true);            
        }else{jPopUpMenuTable.setVisible(false);}
        
       
    }//GEN-LAST:event_jTableProcesosMouseClicked

    private void jItemAgregarFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jItemAgregarFilaMouseClicked
        ptm.addRow(new Proceso());
    }//GEN-LAST:event_jItemAgregarFilaMouseClicked

    private void jItemEliminarFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jItemEliminarFilaMouseClicked
        // TODO add your handling code here:
        ptm.addRow(new Proceso());
    }//GEN-LAST:event_jItemEliminarFilaMouseClicked

    private void jItemAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemAgregarFilaActionPerformed
        // TODO add your handling code here:
        ptm.addRow(new Proceso());
    }//GEN-LAST:event_jItemAgregarFilaActionPerformed

    private void jItemEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEliminarFilaActionPerformed
        ptm.removeRow(jTableProcesos.getSelectedRow());
    }//GEN-LAST:event_jItemEliminarFilaActionPerformed

    private void jButtonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimularActionPerformed
        
        //for (Proceso listProces : ptm.getSelectedRows()) {
        //    if(listProces.isSeleccionado()){
        //        System.out.println(listProces.getNombre());
        //    }
        //};
        if(ptm.getSelectedRows().size()<1){
            mensajeError.setText("Debe seleccionar al menos 1 proceso.");
            mensajeError.setVisible(true);
        }else {
            mensajeError.setText("");
            mensajeError.setVisible(false);
        }
        
        switch(this.algoritmoSeleccionado){
            case("FIFO"):
                //TODO fifo
                FifoView fv = new FifoView(ptm.getSelectedRows());
                fv.setVisible(true);
                break;
            case("SSTF"):
                //TODO scan
                DiscoView dv = new DiscoView(Integer.parseInt(jTextFieldPosicionDisco.getText()), listadoPeticiones);
                dv.setVisible(true);
                break;
            case("LOOK"):
                //TODO LOOK
                break;
            case("SWAPPING"):
                //TODO SWAPPING
                SwappingView sw = new SwappingView(ptm.getSelectedRows());
                sw.setVisible(true);
                break;
            case("LRU"):
                //TODO LRU
                break;
            case("LAMPORT"):
                //TODO LAMPORT
                LamportView lv = new LamportView(ptm.getSelectedRows());
                lv.setVisible(true);
                break;
            default:
                mensajeError.setText(mensajeError.getText() + " Debe seleccionar un Algoritmo.");
                mensajeError.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonSimularActionPerformed

    private void jRBFifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFifoActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "FIFO";
        jPanelDisco.setVisible(false);
        jPanelAlgoritmoPlanificacion.setVisible(true);
    }//GEN-LAST:event_jRBFifoActionPerformed

    
    private void jRBSwappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSwappingActionPerformed
        // TODO add your handling code here:
        this.algoritmoSeleccionado = "SWAPPING";
        jPanelDisco.setVisible(false);
        jPanelAlgoritmoPlanificacion.setVisible(true);
    }//GEN-LAST:event_jRBSwappingActionPerformed

    
    
    private void jRBSwapping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSwapping1ActionPerformed
        
    }//GEN-LAST:event_jRBSwapping1ActionPerformed

   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldPeticionPos.getText().isEmpty()){
            listadoPeticiones.add(Integer.parseInt(jTextFieldPeticionPos.getText()));
            jTAListDisc.setText(jTAListDisc.getText() + "\n" + "Posicion: " + jTextFieldPeticionPos.getText());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDetalleSwappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleSwappingActionPerformed
        jDetalleAlgoritmoSwapping.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleSwappingActionPerformed

    private void jButtonDetalleFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleFIFOActionPerformed
      jDetalleAlgoritmoFifo.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleFIFOActionPerformed

    private void jButtonDetalleScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleScanActionPerformed
        jDetalleAlgoritmoSSTF.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleScanActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jDetalleAlgoritmoDekker.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonDetalleSwapping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleSwapping1ActionPerformed
        jDetalleAlgoritmoPeterson.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleSwapping1ActionPerformed

    private void jButtonDetalleLRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleLRUActionPerformed
        jDetalleAlgoritmoLRU.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleLRUActionPerformed

    private void jRBDekkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDekkerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBDekkerActionPerformed

    private void jButtonDetalleSwapping2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleSwapping2ActionPerformed
        jDetalleAlgoritmoLamport.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleSwapping2ActionPerformed

    private void jButtonDetalleLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleLookActionPerformed
        jDetalleAlgoritmoLook.setVisible(true);
    }//GEN-LAST:event_jButtonDetalleLookActionPerformed

    private void cScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cScanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cScanActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jDetalleAlgoritmocScan.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void SCANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCANActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      jDetalleAlgoritmoScan.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(jRBFifo);
        bg1.add(jRBSSFT);
        bg1.add(jRBLook);
        bg1.add(jRBLRU);
        bg1.add(jRBLamport);
        bg1.add(jRBSwapping);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SCAN;
    private javax.swing.JRadioButton cScan;
    private javax.swing.JDialog jAbout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDetalleFIFO;
    private javax.swing.JButton jButtonDetalleLRU;
    private javax.swing.JButton jButtonDetalleLook;
    private javax.swing.JButton jButtonDetalleScan;
    private javax.swing.JButton jButtonDetalleSwapping;
    private javax.swing.JButton jButtonDetalleSwapping1;
    private javax.swing.JButton jButtonDetalleSwapping2;
    private javax.swing.JButton jButtonSimular;
    private javax.swing.JDialog jDetalleAlgoritmoDekker;
    private javax.swing.JDialog jDetalleAlgoritmoFifo;
    private javax.swing.JDialog jDetalleAlgoritmoLRU;
    private javax.swing.JDialog jDetalleAlgoritmoLamport;
    private javax.swing.JDialog jDetalleAlgoritmoLook;
    private javax.swing.JDialog jDetalleAlgoritmoPeterson;
    private javax.swing.JDialog jDetalleAlgoritmoSSTF;
    private javax.swing.JDialog jDetalleAlgoritmoScan;
    private javax.swing.JDialog jDetalleAlgoritmoSwapping;
    private javax.swing.JDialog jDetalleAlgoritmocScan;
    private javax.swing.JDialog jDocumentation;
    private javax.swing.JMenuItem jItemAgregarFila;
    private javax.swing.JMenuItem jItemEliminarFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlgoritmoSeleccionado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAlgoritmoPlanificacion;
    private javax.swing.JPanel jPanelDisco;
    private javax.swing.JPopupMenu jPopUpMenuTable;
    private javax.swing.JRadioButton jRBDekker;
    private javax.swing.JRadioButton jRBFifo;
    private javax.swing.JRadioButton jRBLRU;
    private javax.swing.JRadioButton jRBLamport;
    private javax.swing.JRadioButton jRBLook;
    private javax.swing.JRadioButton jRBSSFT;
    private javax.swing.JRadioButton jRBSwapping;
    private javax.swing.JRadioButton jRBSwapping1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTAListDisc;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextFieldPeticionPos;
    private javax.swing.JTextField jTextFieldPosicionDisco;
    private javax.swing.JLabel mensajeError;
    // End of variables declaration//GEN-END:variables
}
